package com.ltu.fm.model.location;

import java.util.Date;
import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.google.gson.annotations.Expose;
import com.ltu.fm.configuration.DynamoDBConfiguration;
import com.ltu.fm.utils.AppUtil;

// TODO: Auto-generated Javadoc
/**
 * The Class Location.
 */
@DynamoDBTable(tableName = DynamoDBConfiguration.LOCATION_TABLE_NAME)
public class Location {
	
	/** The id. */
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	@Expose
	private String id;
	
	/** The user id. */
	@DynamoDBIndexHashKey
	@DynamoDBAttribute(attributeName = "userId")
	@Expose
	private String userId;
	
	/** The lng. */
	@DynamoDBAttribute(attributeName = "lng")
	@Expose
	private double lng;
	
	/** The lat. */
	@DynamoDBAttribute(attributeName = "lat")
	@Expose
	private double lat;
	
	/** The created at. */
	@DynamoDBAttribute(attributeName = "createdAt")
	@Expose
	private Date createdAt;

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Gets the user id.
	 *
	 * @return the user id
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * Sets the user id.
	 *
	 * @param userId the new user id
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Gets the lng.
	 *
	 * @return the lng
	 */
	public double getLng() {
		return lng;
	}

	/**
	 * Sets the lng.
	 *
	 * @param lng the new lng
	 */
	public void setLng(double lng) {
		this.lng = lng;
	}

	/**
	 * Gets the lat.
	 *
	 * @return the lat
	 */
	public double getLat() {
		return lat;
	}

	/**
	 * Sets the lat.
	 *
	 * @param lat the new lat
	 */
	public void setLat(double lat) {
		this.lat = lat;
	}

	/**
	 * Gets the created at.
	 *
	 * @return the created at
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * Sets the created at.
	 *
	 * @param createdAt the new created at
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}
	
	/**
	 * Instantiates a new location.
	 */
	public Location() {
		
	}

	/**
	 * Instantiates a new location.
	 *
	 * @param id the id
	 * @param userId the user id
	 * @param lng the lng
	 * @param lat the lat
	 * @param createdAt the created at
	 */
	public Location(String id, String userId, double lng, double lat, Date createdAt) {
		super();
		this.id = id;
		this.userId = userId;
		this.lng = lng;
		this.lat = lat;
		this.createdAt = createdAt;
	}
	
	public Location(Map<String, AttributeValue> item) {
		try {
			this.id = item.get("id").getS();
			this.userId = item.get("userId").getS();
			this.lng = Double.parseDouble(item.get("lng") != null ? item.get("lng").getS() : "0.0");
			this.lat = Double.parseDouble(item.get("lat") != null ? item.get("lat").getS() : "0.0");
			this.createdAt = item.get("createdAt") != null ? AppUtil.toDate(item
					.get("createdAt").getS()) : null;
		} catch (Exception e) {
			//log.error(e.getMessage(), e.getCause());
			//FIXME Phu
		}
	}

}
