package com.ltu.fm.model.friend;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.google.gson.annotations.Expose;
import com.ltu.fm.configuration.DynamoDBConfiguration;

/**
 * User object model - this class is annotated to be used with the DynamoDB
 * object mapper.
 */
@DynamoDBTable(tableName = DynamoDBConfiguration.FRIENDS_TABLE_NAME)
public class Friend{
	/** The id. */
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	@Expose
	private String id;

	/** The user id. */
	@DynamoDBIndexHashKey
	@DynamoDBAttribute(attributeName = "userId")
	@Expose
	private String userId;
	
	/** The other id. */
	@DynamoDBAttribute(attributeName = "otherId")
	@Expose
	private String otherId;
	
	/** The created at. */
	@DynamoDBAttribute(attributeName = "createdAt")
	@Expose
	private Date createdAt; 
		
	/**
	 * Instantiates a new user.
	 */
	public Friend() {

	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Gets the user id.
	 *
	 * @return the user id
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * Sets the user id.
	 *
	 * @param userId the new user id
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * Gets the other id.
	 *
	 * @return the other id
	 */
	public String getOtherId() {
		return otherId;
	}

	/**
	 * Sets the other id.
	 *
	 * @param otherId the new other id
	 */
	public void setOtherId(String otherId) {
		this.otherId = otherId;
	}

	/**
	 * Gets the created at.
	 *
	 * @return the created at
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * Sets the created at.
	 *
	 * @param createdAt the new created at
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * Instantiates a new friend.
	 *
	 * @param id the id
	 * @param userId the user id
	 * @param otherId the other id
	 * @param createdAt the created at
	 */
	public Friend(String id, String userId, String otherId, Date createdAt) {
		this.id = id;
		this.userId = userId;
		this.otherId = otherId;
		this.createdAt = createdAt;
	}
	
	
}


